
import unittest
import pandas as pd
import os
import shutil
import tempfile
import sys
from unittest.mock import patch

# Import the module under test
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import sum_concil

class TestSheetGeneration(unittest.TestCase):
    """
    Test suite specifically for verifying that fully reconciled files
    are exported to separate Excel sheets.
    """

    @classmethod
    def setUpClass(cls):
        """Create a temporary folder structure for tests"""
        cls.test_dir = tempfile.mkdtemp()
        cls.test_accounting_folder = os.path.join(cls.test_dir, 'accounting_files')
        os.makedirs(cls.test_accounting_folder, exist_ok=True)

    @classmethod
    def tearDownClass(cls):
        """Clean up temporary files"""
        shutil.rmtree(cls.test_dir, ignore_errors=True)

    def setUp(self):
        """Clean accounting folder before each test"""
        for f in os.listdir(self.test_accounting_folder):
            os.remove(os.path.join(self.test_accounting_folder, f))

    def _create_test_excel(self, filename, data):
        """Helper to create test Excel files"""
        df = pd.DataFrame(data)
        path = os.path.join(self.test_accounting_folder, filename)
        df.to_excel(path, index=False)
        return path

    def test_reconciled_files_get_own_sheets(self):
        """
        Integration Test: 1 Debt File + 1 Credit File (Perfect Match).
        Verify that 2 extra sheets are created in the output Excel.
        """
        # 1. Setup Data - PERFECT MATCH (Fully Reconciled)
        debt_name = 'M2D-RECU 01.01.2026'
        credit_name = 'M6D-DEV 01.05.2026'
        
        # Filenames must mimic regex pattern 'm2d-recu*.xlsx'
        debt_file = 'm2d-recu 01.01.2026.xlsx'
        credit_file = 'm6d-dev 01.05.2026.xlsx'

        self._create_test_excel(debt_file, {
            'TARJETA': ['1234', '5678'],
            'NUM OPE': ['OP-001', 'OP-002'],
            'IMP VISA': ['$100.00', '$200.00'],
            'RECUPERAR': ['NO', 'NO'] # Must be 'NO' to match standard flow
        })
        
        self._create_test_excel(credit_file, {
            'TARJETA': ['1234', '5678'],
            'NUM OPE': ['OP-001', 'OP-002'],
            'IMP VISA': ['$100.00', '$200.00']
        })

        # 2. Run Conciliation (Mocking FOLDER_PATH)
        output_file = os.path.join(self.test_dir, 'TEST_OUTPUT.xlsx')
        
        # 2. Run Conciliation (Using Conciliator Class)
        output_file = os.path.join(self.test_dir, 'TEST_OUTPUT.xlsx')
        
        # We can instantiate Conciliator directly with the test folder
        c = sum_concil.Conciliator(folder_path=self.test_accounting_folder)
        
        # Mock perform_validations (now an internal method call or just skip validation)
        # Since we are testing sheet generation for valid data, we can just run the full flow
        # But to be safe and match previous logic:
        # We can mock `_check_intra_pile_duplicates` etc if needed, but for this test
        # with perfect data, the real validation should PASS and be fine.
        
        # However, to be 100% sure we don't hit "SUSPICIOUS" errors with our synthetic data:
        with patch.object(c, '_validate_files_are_different', return_value=[]), \
             patch.object(c, '_check_intra_pile_duplicates', return_value=[]):
             
            # Redirect output file: Conciliator.export_results logic
            # The run() method hardcodes the output filename to current dir.
            # We want to control it or change CWD.
            cwd = os.getcwd()
            os.chdir(self.test_dir)
            try:
                c.run()
            finally:
                os.chdir(cwd)

        # 3. Verify Output
        expected_output = os.path.join(self.test_dir, 'CONCILIATION_FINAL_REPORT.xlsx')
        self.assertTrue(os.path.exists(expected_output), "Output file was not created")

        with pd.ExcelFile(expected_output) as xl:
            sheets = xl.sheet_names
            print(f"Generated Sheets: {sheets}")
            
            # Check for Standard Sheets
            self.assertIn('Detailed_Audit_Log', sheets)
            self.assertIn('Fully_Reconciled_Notes', sheets)
            
            # Check for NEW Sheets (The names generated by code)
            # Logic: fname.replace(":", "").replace("/", "-")[:31]
            # M2D-RECU 01.01.2026 -> Matches input
            
            # Be robust about spaces and potential normalization differences
            # Normalized name in sum_concil.py: "M2D-RECU {date}"
            
            self.assertIn(debt_name, sheets, f"Missing Debt File Sheet. Got: {sheets}")
            self.assertIn(credit_name, sheets, f"Missing Credit File Sheet. Got: {sheets}")
            
            # Verify Content of Debt Sheet
            df_debt_sheet = pd.read_excel(xl, sheet_name=debt_name)
            self.assertEqual(len(df_debt_sheet), 2, "Debt sheet should have 2 rows")
            self.assertIn('TARJETA', df_debt_sheet.columns)

if __name__ == '__main__':
    unittest.main(verbosity=2)
